### ISSUE TITLE
Some business architectures templates are not working

### ISSUE THREAD

**Issue by maximenowak** [nocomplexity/ArchitecturePlaybook#1]
Hi, 

Thank you for your playbook, it really looks interesting. When I was quickly running through it, I found 2 outdated links :

- [Basic business architecture template](https://nocomplexity.com/basic-business-architecture-template/)
- [Stakeholder template](https://nocomplexity.com/stakeholder-template/)

Best regards,

Maxime

**Comment by nocomplexity** [comment]
Dear Maxime,

Thanks for your valuable input!
I'm working on an update, also to improve material and remove things that do not serve the main goal of this updated playbook. Some parts still point to dead links. 

Little background: Years ago this playbook was created using WordPress and some (self-made) plugins. Now (2020 Q1) this playbook is updated and migrated towards a Sphinx readthedocs style. So even more open and easier to fork.

Regards, 
Maikel Mardjan

**Comment by nocomplexity** [comment]
Q2-2021: The Shpinx migration worked well, but to make live easier for contributes I swithed to markdown.
Some ToC templates are converted. 
Regards, Maikel
