### ISSUE TITLE
Issue on page /application-architecture.html

### ISSUE THREAD

**Issue by nickrussler** [nocomplexity/ArchitecturePlaybook#12]
In "Short overview of ISO 25010" -> Security:
There is a duplicate entry for "Confidentiality" and "Compliance" is missing.

See: https://nocomplexity.com/documents/arplaybook/quality.html#security

**Comment by nocomplexity** [comment]
Thanks for this valuable input! 
I'll update / correct this to incorporate the crucial 'compliance' function here. 
Regards, Maikel

**Comment by nocomplexity** [comment]
Compliance is no longer part of the updated iso 25010 standard, so removed.

**Comment by nocomplexity** [comment]
Solved, updated repository. Compliance is no longer part of the updated iso 25010 standard, so removed.
