### ISSUE TITLE
businessprinciples.rst has dups on 'maximize benefit to the enterprise'?

### ISSUE THREAD

**Issue by jerryu** [nocomplexity/ArchitecturePlaybook#9]
The businessprinciples.rst has dups on 'maximize benefit to the enterprise'?

Namely, the following two section sharing the same 'statement', and similar 'rationale' and 'implications'.
- Maximise Benefit to the Enterprise  (line136-163)
- Maximize Benefit to the complete enterprise (line164-188)
 
Both sections seem to come from the same commit (a7297f9d circa 2019-11-16), sans cosmetic touchups from two commits (30becd5e and 415549d0)
 
I will be more than happy to put together a patch alone or via collaboration. any insight or context on the original intent(s) would be appreciated.

**Comment by nocomplexity** [comment]
Great input. Thanks!
The section business principles is corrected using this input. On my todo list is sorting the principles and do a review. The key of showing these business principles is 1) as an example and 2) based on experience working on many business architectures past decade. You develop business principles based on a specific business context. But reuse and adjusting is sometimes better that starting from a blank sheet.

Technical; I migrated the businessprinciples file to the simpler markdown format. This book was first created in rst-format. Markdown combined with the addons that Jupyter-book offers is easier to reuse text imho.
Regards, Maikel
